[package]
name = "disp"
version = "0.0.1"
authors = ["Yusuke Tsutsumi <yusuke@tsutsumi.io>"]

[dependencies]
pest = "^1.0"
pest_derive = "^1.0"
getopts = "0.2"
warpspeed = { path = "./warpspeed" }
llvm-sys = "60"

[features]
debug = []
