[package]
name = "warpspeed"
version = "0.1.0"
authors = ["Yusuke Tsutsumi <yusuke@tsutsumi.io>"]

[dependencies]
futures = "0.1"
nix = "0.11"
num_cpus = "1.0"
spmc = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1"
